#!/bin/bash
#jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             bqplot \
                             jupyter-leaflet
